import Head from 'next/head'

import { InteractiveRating } from '@/components/InteractiveRating'

export default function Home() {
  return (
    <>
      <Head>
        <title>JDC | Challenges</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main-container'>
        <h1>Frontend mentor challenges</h1>
        <div className="container container--interactive-rating">
          <InteractiveRating isRated={false} />
        </div>
      </main>
    </>
  )
}
